begin
dbms_metadata.set_transform_param(dbms_metadata.session_transform,'DEFAULT',true);
dbms_metadata.set_transform_param(dbms_metadata.session_transform,'PRETTY',true);
dbms_metadata.set_transform_param(dbms_metadata.session_transform,'SQLTERMINATOR',true);
dbms_metadata.set_transform_param(dbms_metadata.session_transform,'STORAGE',false);
dbms_metadata.set_transform_param(dbms_metadata.session_transform,'SEGMENT_ATTRIBUTES',true);
dbms_metadata.set_transform_param(dbms_metadata.session_transform,'CONSTRAINTS',false);
dbms_metadata.set_transform_param(dbms_metadata.session_transform,'REF_CONSTRAINTS',false);
dbms_metadata.set_transform_param(dbms_metadata.session_transform,'TABLESPACE',true);
end;
/
